version: "3"

services:
  database:
    image: postgres
    container_name: rust_database
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - local

networks:
  local: 
    external: true