FROM postgres:11

ENV POSTGRES_USER docker
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB docker

# Custom initialization scripts
COPY ./init.sh /docker-entrypoint-initdb.d/20-init.sh
COPY schema.sql /schema.sql

RUN chmod +x /docker-entrypoint-initdb.d/20-init.sh